### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by joeblew99** [danieldk/tensorflow#1]
i am a golang programmer and have done some machine learning with python.

I was wondering if there are any decent golang tensorflow examples floating around ?

Sorry this is not a bug...

**Comment by danieldk** [comment]
Not that I know of... This binding assumes that you build the graph in Python and then dump/freeze it. You can then run the graph in Go. So, it's mostly for 'train with Python, deploy with Go scenarios'. If you want to experiment with Tensorflow, it's best to start with the Python API.

**Comment by joeblew99** [comment]
@danieldk thanks for the explanation.

Really help.s

a few days ago i started using https://github.com/chewxy/gorgonia
Its a 100% golang ML system with similarities to tensorflow.
Still early days....
